### ISSUE TITLE
Zusammenarbeit

### ISSUE THREAD

**Issue by Justman10000** [flarum-lang/german#32]
Hi, würde mich gerne mit dir, @Kakifrucht, zusammentun... Also, dieses Paket mit dir zusammen führen...

**Comment by Kakifrucht** [comment]
Wie genau stellst du dir die Zusammenarbeit vor? Leute, die bestehende drittanbieter-Erweiterungen aktualisieren, oder neue hinzufügen möchten sind immer willkommen und gesucht! Wenn es darum geht Änderungen abzusegnen, dann steht dir dazu auch derzeit nichts im Weg.

**Comment by Justman10000** [comment]
> 
> 
> Wie genau stellst du dir die Zusammenarbeit vor? Leute, die bestehende drittanbieter-Erweiterungen aktualisieren, oder neue hinzufügen möchten sind immer willkommen und gesucht! Wenn es darum geht Änderungen abzusegnen, dann steht dir dazu auch derzeit nichts im Weg.

Ja, nur... Bräuchte ich dann hier mehr Rechte, damit ich beispielsweise Datein hochladen kann... Und auch direkt mergen...

**Comment by Kakifrucht** [comment]
Ich werde das Projekt demnächst wohl auch auf Weblate umstellen lassen, dann kannst du per einfachem Webinterface Übersetzungen einfacher hinzufügen. Die werden dann allerdings immernoch von mir überprüft werden, bevor ein neues update veröffentlicht wird.

Vielen dank für deine Beiträge, ich schaue sie mir morgen an.

**Comment by Justman10000** [comment]
Bräuchtest einen Host für Weblate? Könnte die Instanz hosten...

**Comment by Kakifrucht** [comment]
Flarum hat bereits eine öffentliche Instanz der wir dann hinzugefügt werden, aber danke für das Angebot.
Ich schließe das hier mal und kündige die Migration über [unsere Diskussion ](https://discuss.flarum.org/d/2648-german-language-pack) im Forum an.

Danke für deine Mithilfe!

**Comment by Justman10000** [comment]
Wie?

**Comment by Kakifrucht** [comment]
Was ist deine Frage genau?
