### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Justman10000** [flarum-lang/german#43]
When will this actually be updated here?

**Comment by Justman10000** [comment]
@robbot006 

Hallo?

**Comment by Kakifrucht** [comment]
Sorry, I'll handle releasing an update very soon, I just wanted to include some basic docs on the Weblate integration which I haven't gotten around to.

You do not have to wait for a release if you want to use the latest commits in your own Flarum instance. You can edit your composer.json and set the version requirement for flarum-lang/german to "dev-master" and a ``composer update flarum-lang/german`` should pull those updates in.

Thanks for all your contributions!

**Comment by Justman10000** [comment]
> 
> 
> Sorry, I'll handle releasing an update very soon, I just wanted to include some basic docs on the Weblate integration which I haven't gotten around to.
> 
> You do not have to wait for a release if you want to use the latest commits in your own Flarum instance. You can edit your composer.json and set the version requirement for flarum-lang/german to "dev-master" and a `composer update flarum-lang/german` should pull those updates in.
> 
> Thanks for all your contributions!

I could like to help publish updates...

**Comment by Kakifrucht** [comment]
I wanted to go over all translations before I draft a new release, but seeing that you are unstoppable in translating even more stuff and Weblate doesn't seem to have a simple function to check all the latest translations in a simple way (I might be blind) this seems like a daunting task now. I just went over your latest commit and have found a couple of issues with it. Not sure how I will handle it. I'll probably just leave most stuff as it is and hope that if something is off people will see it, register on Weblate and fix it themselves. Then again, the Weblate UI isn't the simplest to use imo.

So this is not just about drafting a new release, but updating docs both here in README and forum, and doing some basic QA.

**Comment by rob006** [comment]
@Kakifrucht You can find new translations using search: https://weblate.rob006.net/languages/de/flarum/search/

![5388cbc9](https://user-images.githubusercontent.com/5972388/132064989-9e3193b4-c29e-4e68-95a4-3e55876921ae.png)

But in general intended workflow is to search for unverified translations and mark them as approved after you review them: https://weblate.rob006.net/languages/de/flarum/search/?type=unapproved

**Comment by Justman10000** [comment]
> 
> 
> Sorry, I'll handle releasing an update very soon, I just wanted to include some basic docs on the Weblate integration which I haven't gotten around to.
> 
> You do not have to wait for a release if you want to use the latest commits in your own Flarum instance. You can edit your composer.json and set the version requirement for flarum-lang/german to "dev-master" and a `composer update flarum-lang/german` should pull those updates in.
> 
> Thanks for all your contributions!

I have changed this in the composer.lock, but Flarum does not react to it! In composer.json, I don't know how to change that:

> "flarum-lang/german": "^1.1",

**Comment by Justman10000** [comment]
Ah habe es mit dem Befehl gelöst:

`composer require flarum-lang/german:dev-master`

**Comment by Kakifrucht** [comment]
@rob006 that seems to work for me, thanks.

Is it possible to bulk change all imported translations as approved?

**Comment by Justman10000** [comment]
> 
> 
> @rob006 that seems to work for me, thanks.
> 
> Is it possible to bulk change all imported translations as approved?

Could I possibly also get admin rights? Could help then too? Könnte dann auch helfen... Because of German and such 😅...

**Comment by Kakifrucht** [comment]
I'm not sure what additional rights that would entail, but you cannot check the translations you do yourself anyways, so I'm not sure how that would help the current situation.

**Comment by rob006** [comment]
> Is it possible to bulk change all imported translations as approved?

You can do bulk status change per component (extension). So for 20 translated components, you need to use this option 20 times. 

![2c661252](https://user-images.githubusercontent.com/5972388/132586476-e3a61867-e79c-4c7c-9299-9e78af3d2c02.png)

It also won't detect which translations were imported, so for some mixed-state components you may need to review translations manually, one by one.. Using zen mode may speed-up review in this case.

**Comment by Kakifrucht** [comment]
Yes I found that option, was hoping that there is some way to do it for all at once before a given date.

**Comment by Justman10000** [comment]
> 
> 
> I'm not sure what additional rights that would entail, but you cannot check the translations you do yourself anyways, so I'm not sure how that would help the current situation.

I could test it out...

**Comment by Justman10000** [comment]
@Kakifrucht 

Hello?

**Comment by Kakifrucht** [comment]
Whats your question? Giving you "admin rights" (whatever that means in this context) would not make QA of your translations any more viable.

**Comment by Justman10000** [comment]
> ...would not make QA of your translations any more viable.

Like mine?

**Comment by Kakifrucht** [comment]
What I'm saying is that we need someone else to look over all new translations you did.

**Comment by Justman10000** [comment]
> 
> 
> What I'm saying is that we need someone else to look over all new translations you did.

How come? Can i do?

**Comment by Justman10000** [comment]
> What I'm saying is that we need someone else to look over all new translations you did.

So, as far as I can think of, as an administrator you have rights to everything, so you can also proofreading... If not, I'd like at least proofread rights, since I've already translated over 2,139 strings!

**Comment by Kakifrucht** [comment]
I'm not sure what those rights exactly are, are you saying that you cannot edit translations, only add new ones?
If that is the case you should definitely have all necessary rights granted to you.

**Comment by Justman10000** [comment]
> I'm not sure what those rights exactly are, are you saying that you cannot edit translations, only add new ones? If that is the case you should definitely have all necessary rights granted to you.

What I meant is that with the proofreading rights I can check translations, thus approve them... As far as I understand, translations have to be checked in order for them to be included in the stable, otherwise they are only available in the dev build

**Comment by Kakifrucht** [comment]
Depends on how we would handle it. Translations don't need to be set to approved to be synced to this repository, all translations you have done via Weblate should be on GitHub.

Personally I don't see myself going through all the translations you have done and 'approving' them, so we will just keep it as is until somebody wants to change/improve/fix them. Let me know if you lack any privileges on Weblate to change stuff though.

Version 1.2.0 should thus include all the translations you have done.

**Comment by Justman10000** [comment]
> Depends on how we would handle it. Translations don't need to be set to approved to be synced to this repository, all translations you have done via Weblate should be on GitHub.
> 
> Personally I don't see myself going through all the translations you have done and 'approving' them, so we will just keep it as is until somebody wants to change/improve/fix them. Let me know if you lack any privileges on Weblate to change stuff though.
> 
> Version 1.2.0 should thus include all the translations you have done.

Well, the weird thing was, once I had the stable, my translations weren't accepted! I don't know how long I waited there, or how long it takes for the translations to be pushed from Weblate to the repository! Anyway, when I switched to the dev version, my translations were right there!

**Comment by Justman10000** [comment]
p

**Comment by rob006** [comment]
> Well, the weird thing was, once I had the stable, my translations weren't accepted! I don't know how long I waited there, or how long it takes for the translations to be pushed from Weblate to the repository! Anyway, when I switched to the dev version, my translations were right there!

It has nothing to do with approving translations on Weblate. Translations are exported to language pack repository even if they're not approved, but they're pushed to `master` branch. In order to make them available  as "stable" in Composer, someone needs to tag new release on GitHub. If you don't want to wait for that, using `composer require flarum-lang/german:dev-master` is a right call.

**Comment by Justman10000** [comment]
> > Well, the weird thing was, once I had the stable, my translations weren't accepted! I don't know how long I waited there, or how long it takes for the translations to be pushed from Weblate to the repository! Anyway, when I switched to the dev version, my translations were right there!
> 
> It has nothing to do with approving translations on Weblate. Translations are exported to language pack repository even if they're not approved, but they're pushed to `master` branch. In order to make them available as "stable" in Composer, someone needs to tag new release on GitHub. If you don't want to wait for that, using `composer require flarum-lang/german:dev-master` is a right call.

Then could I do this? I mean, tag new releases on GitHub?

**Comment by rob006** [comment]
No, only language pack maintainers can do this.

**Comment by Justman10000** [comment]
> No, only language pack maintainers can do this.

Then could I be one?

**Comment by Kakifrucht** [comment]
I have commited to tagging releases more frequently after I see sufficient changes made, if that doesn't work out we can talk about adding you as maintainer to tag releases.

I'm going to close this, but feel free to use it in case you believe a release should be tagged and I haven't yet done so.

**Comment by Justman10000** [comment]
> 

Well, if I were a maintainer, you would have less work 😅

**Comment by Kakifrucht** [comment]
I don't mind doing some basic looking over the commits and drafting a release, but If I that changes I'll let you know!
