### ISSUE TITLE
mentioned_by_text & mentioned_by_self_text keys are broken.

### ISSUE THREAD

**Issue by iPurpl3x** [flarum-lang/german#45]
See https://github.com/flarum-lang/german/blob/a1913c6dfa7a94b41c1b75ed25808d34cdc7bd33/locale/flarum-mentions.yml#L26

Compared to https://github.com/flarum/mentions/blob/51ec61799193c7a449650157885d670b89a3c34b/locale/en.yml#L33

Maybe there is more that is broken...

**Comment by iPurpl3x** [comment]
@Kakifrucht cna you take a look?

**Comment by Kakifrucht** [comment]
I'm not sure what you believe is broken here?
Does the translation not work on your instance of Flarum?

**Comment by Kakifrucht** [comment]
Ah nevermind, I just got it, the placeholder is outdated. Thanks for reporting, I'll look into it.

**Comment by Kakifrucht** [comment]
This is interesting since this translation was never changed. This mistakes goes back to the first translated version of flarum-mentions and no one ever caught it. I always thought that the way it doesn't show the username is the default behaviour on my forum!

**Comment by iPurpl3x** [comment]
Oh wow, yes that is indeed very interesting!
Now I saw that old instances (beta.13) also have this, so yes you're right, no one noticed since the beginning...

**Comment by iPurpl3x** [comment]
@Kakifrucht could you tell me when do you plan to fix this?

**Comment by Kakifrucht** [comment]
It is already fixed however no release has been tagged. The reason for the missing release is the fact that there are still tons of new translations which are unchecked and I lack the motivation to go over them, it has gotten too much for me alone (see ticket #43). 

I could tag a release as is but I'm not sure I want to do that just skipping all the QA that's left to do.
You can also ignore releases and set your version of this language pack to dev-master to get all the latest stuff in your instance.

You (and everybody who's interested) could help though by signing up to Weblate, choosing some extensions and correcting/improving translations if you find any issues with them. Not sure if I can keep it up for the future anyways.

**Comment by iPurpl3x** [comment]
Sure, I understand. I'll see what I can do when I have some time.

So I will close this issue, as you say it has been solved.
