### ISSUE TITLE
Mentions has a wrong translation

### ISSUE THREAD

**Issue by iPurpl3x** [flarum-lang/german#47]
See https://weblate.rob006.net/translate/flarum/flarum-mentions/de/?sort_by=-priority%2Cposition&offset=9#suggestions

Please make that suggested change effective @robbot006 or @Kakifrucht

**Comment by Kakifrucht** [comment]
I don't understand the change, wouldn't that cause a translation of "iPurpl3x hast auf deinen Beitrag geantwortet"?

**Comment by iPurpl3x** [comment]
@Kakifrucht I made a mistake and did a suggestion on two string: this is the right one: 
https://weblate.rob006.net/translate/flarum/flarum-mentions/de/?sort_by=-priority%2Cposition&offset=8#suggestions
(`flarum-mentions.forum.post.mentioned_by_self_text`)

So this is "by self", so it would become "**Du** hast..."

**Comment by Kakifrucht** [comment]
Ah yes that is indeed right, thanks for pointing it out!
Fix approved.
